output.directory=joularjx-result

logging.enabled=true

logging.level=INFO

measurement.mode=method

sampling.interval=1000

track.cpu=true

track.package=true

track.dram=true

include.system.info=true

powermonitor-path=C:\\Windows\\System32